language: cpp
dist: trusty
sudo: required
compiler: gcc
install:
# C++14
- sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
- sudo apt-get update
- sudo apt-get install gcc-5 g++-5
- sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-5 90
- sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-5 90
# cmake 3.2
- sudo apt-get install software-properties-common
- sudo add-apt-repository ppa:george-edison55/cmake-3.x
- sudo apt-get update
- sudo apt-get install cmake
- cd build
- sudo -E bash deps_ubuntu_14.04.sh
script:
- cd build
- cmake ..
- make
- make test
